import { defineConfig, loadEnv } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';
import { resolve } from 'path';
import os from 'os';

const bundleAnalyzer = process.env.ANALYZE === 'true'
    ? (await import('rollup-plugin-visualizer')).visualizer({ template: 'treemap', filename: 'stats.html', gzipSize: true })
    : null;

// Load env files manually (Vite hasn't loaded them yet at config evaluation time)
const env = loadEnv('development', process.cwd(), '');

const DEV_PORT = parseInt(env.VITE_DEV_PORT, 10) || 5173;

// scripts/lan-ip.mjs writes VITE_DEV_SERVER_URL to .env.local automatically
const devServerUrl = env.VITE_DEV_SERVER_URL
    ? new URL(env.VITE_DEV_SERVER_URL)
    : null;

// Determine the external host/IP for network access
let externalHost = null;
if (devServerUrl) {
    externalHost = devServerUrl.hostname;
} else {
    // Fallback: detect LAN IP from system network interfaces
    try {
        const interfaces = os.networkInterfaces();
        for (const name of Object.keys(interfaces)) {
            for (const iface of interfaces[name] ?? []) {
                if (iface.family === 'IPv4' && !iface.internal) {
                    externalHost = iface.address;
                    break;
                }
            }
            if (externalHost) break;
        }
    } catch {}
}

const useExternalAccess = externalHost
    && externalHost !== 'localhost'
    && externalHost !== '127.0.0.1';

// server.origin controls the base URL for script/link tags generated by @vite
const serverOrigin = useExternalAccess
    ? (devServerUrl ? devServerUrl.origin : `http://${externalHost}:${DEV_PORT}`)
    : undefined;

// hmr.host controls the WebSocket HMR connection host
const hmrHost = useExternalAccess ? externalHost : undefined;

export default defineConfig({
    plugins: [
        laravel({
            input: 'resources/js/app.ts',
            refresh: true,
        }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
        bundleAnalyzer,
    ].filter(Boolean),
    resolve: {
        alias: {
            '@': resolve(__dirname, 'resources/js'),
            // Use vue-i18n runtime-only build — removes the message compiler
            // that requires unsafe-eval, making our CSP stricter and safer
            'vue-i18n': 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js',
        },
    },
    optimizeDeps: {
        include: [
            'vue',
            '@inertiajs/vue3',
            '@vueuse/core',
            'vue-i18n',
            'lucide-vue-next',
            'reka-ui',
            'class-variance-authority',
            'clsx',
            'tailwind-merge',
        ],
    },
    server: {
        host: '0.0.0.0',
        port: DEV_PORT,
        strictPort: true,
        origin: serverOrigin,
        cors: {
            origin: '*',
        },
        hmr: {
            host: hmrHost,
            overlay: true,
        },
        watch: {
            usePolling: true,
            interval: 1000,
        },
    },
    build: {
        rollupOptions: {
            output: {
                manualChunks(id) {
                    if (id.includes('node_modules/vue-i18n')) {
                        return 'vendor-i18n';
                    }
                    if (id.includes('node_modules/vue/') || id.includes('node_modules/@inertiajs/vue3') || id.includes('node_modules/@vueuse')) {
                        return 'vendor-vue';
                    }
                    if (id.includes('node_modules/reka-ui') || id.includes('node_modules/radix-vue') || id.includes('node_modules/class-variance-authority') || id.includes('node_modules/clsx') || id.includes('node_modules/tailwind-merge') || id.includes('node_modules/tailwindcss-animate')) {
                        return 'vendor-ui';
                    }
                    if (id.includes('node_modules/lucide-vue-next')) {
                        return 'vendor-icons';
                    }
                },
            },
        },
    },
});
